version: "3.9"

services:
  admin_nginx:
    image: nginx:stable-alpine
    ports:
      - published: 80
        target: 80
        mode: host
      - published: 443
        target: 443
        mode: host
    volumes:
      - admin_files:/var/www/mikbill/admin:ro
    configs:
      - source: admin_nginx_site
        target: /etc/nginx/conf.d/default.conf
      - source: admin_nginx_ssl_cert
        target: /etc/nginx/ssl/fullchain.pem
      - source: admin_nginx_ssl_key
        target: /etc/nginx/ssl/privkey.pem
    environment:
      - TZ=Europe/Kiev
    networks:
      admin_network: {}
    deploy:
      placement:
        constraints:
          - node.hostname==mb-admin

  admin_redis:
    image: redis:alpine3.18
    environment:
      - TZ=Europe/Kiev
    networks:
      admin_network: {}
    deploy:
      placement:
        constraints:
          - node.hostname==mb-admin

  admin_php:
    image: nekkoy/admin:latest
    environment:
      - TZ=Europe/Kiev
      - MIKBILL_MYSQL_HOST=mysql_balancer
      - MIKBILL_MYSQL_USERNAME=mikbill
      - MIKBILL_MYSQL_PASSWORD=mikbill
      - MIKBILL_MYSQL_DATABASE=mikbill
      - MIKBILL_MYSQL_CHARSET=utf8mb4
      - MIKBILL_DEBUG=false
      - MIKBILL_ERROR_LOG=/var/log/mikbill_general.log
      - MIKBILL_DEBUG_LOG=/var/log/mikbill_debug.log
    volumes:
      - admin_files:/var/www/mikbill/admin
    configs:
      - source: admin_php_ini
        target: /usr/local/etc/php/php.ini
      - source: admin_php_fpm
        target: /usr/local/etc/php-fpm.d/www.conf
      - source: mikbill_licence_key
        target: /var/mikbill/license/client.key
      - source: mikbill_licence_crt
        target: /var/mikbill/license/serv.crt
    networks:
      database_network: {}
      admin_network: {}
    deploy:
      mode: replicated
      replicas: 3
      placement:
        constraints:
          - node.hostname==mb-admin

volumes:
  admin_files:

configs:
  admin_nginx_site:
    file: files/nginx/site.conf
  admin_nginx_ssl_cert:
    file: files/nginx/ssl/fullchain.pem
  admin_nginx_ssl_key:
    file: files/nginx/ssl/privkey.pem
  admin_php_ini:
    file: files/php/php.ini
  admin_php_fpm:
    file: files/php/www.conf
  mikbill_licence_key:
    file: ../license/client.key
  mikbill_licence_crt:
    file: ../license/serv.crt

networks:
  database_network:
    external: true
    name: database_network
  admin_network:
    external: true
    name: admin_network