version: "3.9"

services:
  mysql_backup:
    build:
      dockerfile: ./build/mysql_client.docker
    env_file:
      - .env
    command: >
      sh -c "mysqldump ${MYSQL_BACKUP_OPTS} -h ${MYSQL_HOST} -u root -p${ROOT_PASSWORD} ${MIKBILL_DATABASE} >> ${MYSQL_BACKUP_DIR}/mikbill.sql &&
      mv ${MYSQL_BACKUP_DIR}/mikbill.sql ${MYSQL_BACKUP_DIR}/mikbill_`date +%F`.sql &&
      gzip ${MYSQL_BACKUP_DIR}/mikbill_`date +%F`.sql"
    networks:
      cluster_network: {}
    volumes:
      - "./backup:${MYSQL_BACKUP_DIR}"
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 256M
        reservations:
          cpus: "1"
          memory: 256M

networks:
  cluster_network:
    external: true
    name: cluster_network