version: "3.9"

services:
  mysql_procedure:
    build:
      dockerfile: ./build/mysql_client.docker
    env_file:
      - .env
    command: >
      sh -c "mysql -h ${MYSQL_HOST} -u root -p${ROOT_PASSWORD} ${MIKBILL_DATABASE} -e '\source /tmp/mikbill/proc.sql'"
    networks:
      cluster_network: {}
    volumes:
      - "./sql/proc8.sql:/tmp/mikbill/proc.sql"

networks:
  cluster_network:
    external: true
    name: cluster_network