services:
  pma_template:
    image: ${PMA_IMAGE}
    networks:
      - database_network
    ports:
      - "${PMA_PORT}:80"
    environment:
      - PMA_HOST=${MYSQL_HOST}
      - PMA_PMAD=${MYSQL_DATABASE}
    resources:
      limits:
        cpus: "${PMA_CPU}"
        memory: ${PMA_RAM}

  balancer_template:
    image: ${BALANCER_IMAGE}
    networks:
      - database_network
      - cluster_network
    ports:
      - "3306:3306"
    volumes:
      - ./conf/balancer.conf:/etc/nginx/nginx.conf
    restart: unless-stopped
    resources:
      limits:
        cpus: "${BALANCER_CPU}"
        memory: ${BALANCER_RAM}

  arbitrator_template:
    build:
      dockerfile: ./build/arbitrator.docker # https://docs.percona.com/percona-xtradb-cluster/8.0/release-notes/8.0.33-25.upd.html
    networks:
      - cluster_network
    restart: unless-stopped
    resources:
      limits:
        cpus: "${ARBITRATOR_CPU}"
        memory: ${ARBITRATOR_RAM}

  cluster_template:
    image: ${CLUSTER_IMAGE}
    networks:
      - cluster_network
    environment:
      - CLUSTER_NAME=${CLUSTER_GROUPNAME}
      - MYSQL_ROOT_PASSWORD=${ROOT_PASSWORD}
      - MYSQL_ROOT_HOST=${ROOT_HOST}
      - MYSQL_USER=${MIKBILL_USER}
      - MYSQL_PASSWORD=${MIKBILL_PASSWORD}
      - MYSQL_DATABASE=${MIKBILL_DATABASE}
    volumes:
      - ./scripts/init.sh:/init.sh
      - ./certs:/certs
    entrypoint: ["/init.sh"]
    command: --default-time-zone='${TZ}'
    configs:
      - source: cluster_config
        target: /etc/node.cnf
        uid: '1'
        gid: '1'
        mode: 0664
    restart: unless-stopped
    resources:
      limits:
        cpus: "${CLUSTER_CPU}"
        memory: ${CLUSTER_RAM}