version: '3.9'

services:
  node3:
    hostname: node3
    extends:
      file: ./services.yml
      service: cluster_template
    volumes:
      - cluster_node3:/var/lib/mysql
    environment:
      - CLUSTER_JOIN=arbitrator
      - CLUSTER_ADDRESS=${ARBITRATOR_NODES}
    networks:
      - cluster_network

configs:
  cluster_config:
    file: ./conf/node_cluster.cnf

volumes:
  cluster_node3:

networks:
  cluster_network:
    external: true
    name: cluster_network