version: "3.9"

services:
  cabinetapi_nginx:
    image: nginx:stable-alpine
    environment:
      - TZ=Europe/Kiev
    ports:
      - published: 80
        target: 80
        mode: host
      - published: 443
        target: 443
        mode: host
    volumes:
      -  cabinetapi_files:/var/www/cabinetapi:ro
    configs:
      - source: cabinetapi_nginx_site
        target: /etc/nginx/conf.d/default.conf
      - source: cabinetapi_nginx_ssl_cert
        target: /etc/nginx/conf.d/ssl/fullchain.pem
      - source: cabinetapi_nginx_ssl_key
        target: /etc/nginx/conf.d/ssl/privkey.pem
      - source: mikbill_licence_key
        target: /var/mikbill/license/client.key
      - source: mikbill_licence_crt
        target: /var/mikbill/license/serv.crt
    networks:
      cabinetapi_network: {}
    deploy:
      placement:
        constraints:
          - node.hostname==mb-payments

  cabinetapi_php:
    image: nekkoy/cabinet_api:latest
    environment:
      - TZ=Europe/Kiev
      - MIKBILL_MYSQL_HOST=mysql_balancer
      - MIKBILL_MYSQL_USERNAME=mikbill
      - MIKBILL_MYSQL_PASSWORD=mikbill
      - MIKBILL_MYSQL_DATABASE=mikbill
      - MIKBILL_MYSQL_CHARSET=utf8mb4
      - MIKBILL_DEBUG=false
      - MIKBILL_ERROR_LOG=/var/log/mikbill_general.log
      - MIKBILL_DEBUG_LOG=/var/log/mikbill_debug.log
    volumes:
      - cabinetapi_files:/var/www/cabinetapi
    networks:
      database_network: {}
      cabinetapi_network: {}
    deploy:
      placement:
        constraints:
          - node.hostname==mb-payments

volumes:
  cabinetapi_files:

configs:
  cabinetapi_nginx_site:
    file: files/nginx/site.conf
  cabinetapi_nginx_ssl_cert:
    file: files/nginx/ssl/fullchain.pem
  cabinetapi_nginx_ssl_key:
    file: files/nginx/ssl/privkey.pem
  mikbill_licence_key:
    file: ../license/client.key
  mikbill_licence_crt:
    file: ../license/serv.crt

networks:
  database_network:
    external: true
    name: database_network
  cabinetapi_network:
    external: true
    name: cabinetapi_network