version: "3.9"

services:
  cabinet_nginx:
    image: nginx:stable-alpine
    environment:
      - TZ=Europe/Kiev
    ports:
      - published: 88
        target: 80
        mode: host
      - published: 444
        target: 443
        mode: host
    volumes:
      - cabinet_files:/var/www/mikbill/stat:ro
    configs:
      - source: cabinet_nginx_site
        target: /etc/nginx/conf.d/default.conf
      - source: cabinet_nginx_ssl_cert
        target: /etc/nginx/conf.d/ssl/fullchain.pem
      - source: cabinet_nginx_ssl_key
        target: /etc/nginx/conf.d/ssl/privkey.pem
    networks:
      cabinet_network: {}

  cabinet_php:
    image: nekkoy/cabinet:latest
    environment:
      - TZ=Europe/Kiev
      - MIKBILL_MYSQL_HOST=mysql
      - MIKBILL_MYSQL_USERNAME=mikbill
      - MIKBILL_MYSQL_PASSWORD=mikbill
      - MIKBILL_MYSQL_DATABASE=mikbill
      - MIKBILL_MYSQL_CHARSET=utf8mb4
      - MIKBILL_DEBUG=false
      - MIKBILL_ERROR_LOG=/var/log/mikbill/stat/general.log
      - MIKBILL_DEBUG_LOG=/var/log/mikbill/stat/debug.log
    volumes:
      - cabinet_files:/var/www/mikbill/stat
    configs:
      - source: mikbill_licence_key
        target: /var/mikbill/license/client.key
      - source: mikbill_licence_crt
        target: /var/mikbill/license/serv.crt
    networks:
      database_network: {}
      cabinet_network: {}

volumes:
  cabinet_files:

configs:
  cabinet_nginx_site:
    file: files/nginx/site.conf
  cabinet_nginx_ssl_cert:
    file: files/nginx/ssl/fullchain.pem
  cabinet_nginx_ssl_key:
    file: files/nginx/ssl/privkey.pem
  mikbill_licence_key:
    file: ../license/client.key
  mikbill_licence_crt:
    file: ../license/serv.crt

networks:
  database_network:
    external: true
    name: database_network
  cabinet_network:
    external: true
    name: cabinet_network